---
# drone config
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/packethost/csi-packet

steps:
- name: test
  pull: always
  image: golang:1.12-alpine
  commands:
  - apk --update add make git
  - make ci

---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

## publish git tagged and latest images

steps:
- name: publish-amd64
  pull: always
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: packethost/csi-packet
    build_args:
      - BINARCH=amd64
      - REPOARCH=amd64
    tags:
    - "${DRONE_COMMIT}-amd64"
    - latest-amd64
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event: push

## publish release image

- name: release-amd64
  pull: always
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: packethost/csi-packet
    build_args:
      - BINARCH=amd64
      - REPOARCH=amd64
    tags:
    - "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

## publish git tagged and latest images

steps:
- name: publish-arm64
  pull: always
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: packethost/csi-packet
    build_args:
      - BINARCH=arm64
      - REPOARCH=arm64v8
    tags:
    - "${DRONE_COMMIT}-arm64"
    - latest-arm64
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event: push

## publish release image

- name: release-arm64
  pull: always
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: packethost/csi-packet
    build_args:
      - BINARCH=arm64
      - REPOARCH=arm64v8
    tags:
    - "${DRONE_TAG}-arm64"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

---
kind: pipeline
name: manifests

depends_on:
- amd64
- arm64

platform:
  os: linux
  arch: amd64

## manifests

steps:
- name: manifest-commit
  pull: always
  image: plugins/manifest
  settings:
    target: "packethost/csi-packet:${DRONE_COMMIT}"
    template: "packethost/csi-packet:${DRONE_COMMIT}-ARCH"
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event: push

- name: manifest-latest
  pull: always
  image: plugins/manifest
  settings:
    target: packethost/csi-packet:latest
    template: packethost/csi-packet:latest-ARCH
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event: push

## Releases

- name: release-manifest-commit
  pull: always
  image: plugins/manifest
  settings:
    target: "packethost/csi-packet:${DRONE_TAG}"
    template: "packethost/csi-packet:${DRONE_TAG}-ARCH"
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    username:
      from_secret: docker_username
  when:
    event:
      - tag
